aws-load-balancer-controller:
  serviceAccount:
    create: false
  image:
    repository: 602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon/aws-load-balancer-controller
    tag: v2.4.3
    pullPolicy: IfNotPresent
